version: '3.4'

services:

  traefik:
    command: --api --docker --docker.exposedbydefault=false

  api:
    command: npm run dev
    volumes:
      - ./deps/back:/usr/app
      - /usr/app/node_modules